[[main]]
name = "About"
pageRef = "/"
weight = 1

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 2

[[main]]
identifier = "instagram"
pre = "instagram"
url = "https://instagram.com/ost.sd"
weight = 3
