[[main]]
name = "About"
pageRef = "/"
weight = 1

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 2

[[main]]
name = "Join"
pageRef = "/join"
weight = 3

[[main]]
identifier = "instagram"
pre = "instagram"
url = "https://instagram.com/ost.sd"
weight = 4

[[main]]
identifier = "youtube"
pre = "youtube"
url = "https://www.youtube.com/channel/UCZLYUxWMkFkF1rVwBdebUrg"
weight = 3