autoSwitchAppearance = false 
colorScheme = "test2" 
defaultAppearance = "dark" # valid options: light or dark
disableImageOptimization = true 
disableTextInHeader = true 
enableCodeCopy = false 
enableSearch = false 

# mainSections = ["posts"]
# robots = ""

[header]
layout = "custom" # valid options: basic, fixed
showAppearanceSwitcher = false 

[footer]
showAppearanceSwitcher = false
showCopyright = true
showMenu = true
showScrollToTop = true
showThemeAttribution = false

[homepage]
cardView = true 
cardViewScreenWidth = false 
homepageImage = "img/background.webm" # used in: hero, and card
layout = "custom" # valid options: page, profile, hero, card, background, custom
layoutBackgroundBlur = false 
showMoreLink = false 
# showMoreLinkDest = "/blowfish_artist/posts" 
showRecent = true
showRecentItems = 3
backContactImage = "img/back_contact.jpg"
